title: Chicago Crime Analysis
description: "Evaluating the impacts of Chicago Public School closures on school-related crime."
url: "https://Radixon25.github.io"
baseurl: "/Crime_Estimation" # Matches repo name
repository: "Radixon25/Crime_Estimation"

exclude:
  - docs/_posts
  - test/_posts
  - _posts

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

# Author details (optional)
author:
  name   : "Rashad Dixon"
  avatar : "/assets/profile.jpg"
  bio    : "Researcher focused on urban policy and causal inference."
  location: "Chicago, IL"
  github : "Radixon25"
