title: Chicago Crime Analysis
description: "Evaluating the impacts of Chicago Public School closures on school-related crime."
url: "https://Radixon25.github.io"
baseurl: "/Crime_Estimation" # Matches repo name
repository: "Radixon25/Crime_Estimation"

# Theme settings
theme: minimal-mistakes-jekyll

# Author details (optional)
author:
  name   : "Rashad Dixon"
  avatar : "/assets/profile.jpg"
  bio    : "Researcher focused on urban policy and causal inference."
  location: "Chicago, IL"
  github : "Radixon25"
